/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedExecutiveInfoRouteImport } from './routes/_authenticated/executive-info'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompletedRouteImport } from './routes/_authenticated/completed'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedApplicantsRouteImport } from './routes/_authenticated/applicants'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts.index'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts.$id'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as ApiPublicV1TasksIndexRouteImport } from './routes/api/public/v1/tasks.index'
import { Route as ApiPublicV1ContactsIndexRouteImport } from './routes/api/public/v1/contacts.index'
import { Route as ApiPublicV1TasksIdRouteImport } from './routes/api/public/v1/tasks.$id'
import { Route as ApiPublicV1ContactsIdRouteImport } from './routes/api/public/v1/contacts.$id'
import { Route as ApiPublicV1TasksIdNudgeRouteImport } from './routes/api/public/v1/tasks.$id.nudge'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutiveInfoRoute =
  AuthenticatedExecutiveInfoRouteImport.update({
    id: '/executive-info',
    path: '/executive-info',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompletedRoute = AuthenticatedCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicantsRoute = AuthenticatedApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TasksIndexRoute = ApiPublicV1TasksIndexRouteImport.update({
  id: '/api/public/v1/tasks/',
  path: '/api/public/v1/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ContactsIndexRoute =
  ApiPublicV1ContactsIndexRouteImport.update({
    id: '/api/public/v1/contacts/',
    path: '/api/public/v1/contacts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TasksIdRoute = ApiPublicV1TasksIdRouteImport.update({
  id: '/api/public/v1/tasks/$id',
  path: '/api/public/v1/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ContactsIdRoute = ApiPublicV1ContactsIdRouteImport.update({
  id: '/api/public/v1/contacts/$id',
  path: '/api/public/v1/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TasksIdNudgeRoute = ApiPublicV1TasksIdNudgeRouteImport.update({
  id: '/nudge',
  path: '/nudge',
  getParentRoute: () => ApiPublicV1TasksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applicants': typeof AuthenticatedApplicantsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/completed': typeof AuthenticatedCompletedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/executive-info': typeof AuthenticatedExecutiveInfoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/contacts/$id': typeof ApiPublicV1ContactsIdRoute
  '/api/public/v1/tasks/$id': typeof ApiPublicV1TasksIdRouteWithChildren
  '/api/public/v1/contacts/': typeof ApiPublicV1ContactsIndexRoute
  '/api/public/v1/tasks/': typeof ApiPublicV1TasksIndexRoute
  '/api/public/v1/tasks/$id/nudge': typeof ApiPublicV1TasksIdNudgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applicants': typeof AuthenticatedApplicantsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/completed': typeof AuthenticatedCompletedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/executive-info': typeof AuthenticatedExecutiveInfoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/contacts/$id': typeof ApiPublicV1ContactsIdRoute
  '/api/public/v1/tasks/$id': typeof ApiPublicV1TasksIdRouteWithChildren
  '/api/public/v1/contacts': typeof ApiPublicV1ContactsIndexRoute
  '/api/public/v1/tasks': typeof ApiPublicV1TasksIndexRoute
  '/api/public/v1/tasks/$id/nudge': typeof ApiPublicV1TasksIdNudgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/applicants': typeof AuthenticatedApplicantsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/completed': typeof AuthenticatedCompletedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/executive-info': typeof AuthenticatedExecutiveInfoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/contacts/$id': typeof ApiPublicV1ContactsIdRoute
  '/api/public/v1/tasks/$id': typeof ApiPublicV1TasksIdRouteWithChildren
  '/api/public/v1/contacts/': typeof ApiPublicV1ContactsIndexRoute
  '/api/public/v1/tasks/': typeof ApiPublicV1TasksIndexRoute
  '/api/public/v1/tasks/$id/nudge': typeof ApiPublicV1TasksIdNudgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/applicants'
    | '/calendar'
    | '/completed'
    | '/dashboard'
    | '/executive-info'
    | '/settings'
    | '/contacts/$id'
    | '/contacts/'
    | '/api/public/google/callback'
    | '/api/public/v1/health'
    | '/api/public/v1/contacts/$id'
    | '/api/public/v1/tasks/$id'
    | '/api/public/v1/contacts/'
    | '/api/public/v1/tasks/'
    | '/api/public/v1/tasks/$id/nudge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/applicants'
    | '/calendar'
    | '/completed'
    | '/dashboard'
    | '/executive-info'
    | '/settings'
    | '/contacts/$id'
    | '/contacts'
    | '/api/public/google/callback'
    | '/api/public/v1/health'
    | '/api/public/v1/contacts/$id'
    | '/api/public/v1/tasks/$id'
    | '/api/public/v1/contacts'
    | '/api/public/v1/tasks'
    | '/api/public/v1/tasks/$id/nudge'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/applicants'
    | '/_authenticated/calendar'
    | '/_authenticated/completed'
    | '/_authenticated/dashboard'
    | '/_authenticated/executive-info'
    | '/_authenticated/settings'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/contacts/'
    | '/api/public/google/callback'
    | '/api/public/v1/health'
    | '/api/public/v1/contacts/$id'
    | '/api/public/v1/tasks/$id'
    | '/api/public/v1/contacts/'
    | '/api/public/v1/tasks/'
    | '/api/public/v1/tasks/$id/nudge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1ContactsIdRoute: typeof ApiPublicV1ContactsIdRoute
  ApiPublicV1TasksIdRoute: typeof ApiPublicV1TasksIdRouteWithChildren
  ApiPublicV1ContactsIndexRoute: typeof ApiPublicV1ContactsIndexRoute
  ApiPublicV1TasksIndexRoute: typeof ApiPublicV1TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive-info': {
      id: '/_authenticated/executive-info'
      path: '/executive-info'
      fullPath: '/executive-info'
      preLoaderRoute: typeof AuthenticatedExecutiveInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/completed': {
      id: '/_authenticated/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof AuthenticatedCompletedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applicants': {
      id: '/_authenticated/applicants'
      path: '/applicants'
      fullPath: '/applicants'
      preLoaderRoute: typeof AuthenticatedApplicantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tasks/': {
      id: '/api/public/v1/tasks/'
      path: '/api/public/v1/tasks'
      fullPath: '/api/public/v1/tasks/'
      preLoaderRoute: typeof ApiPublicV1TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/contacts/': {
      id: '/api/public/v1/contacts/'
      path: '/api/public/v1/contacts'
      fullPath: '/api/public/v1/contacts/'
      preLoaderRoute: typeof ApiPublicV1ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tasks/$id': {
      id: '/api/public/v1/tasks/$id'
      path: '/api/public/v1/tasks/$id'
      fullPath: '/api/public/v1/tasks/$id'
      preLoaderRoute: typeof ApiPublicV1TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/contacts/$id': {
      id: '/api/public/v1/contacts/$id'
      path: '/api/public/v1/contacts/$id'
      fullPath: '/api/public/v1/contacts/$id'
      preLoaderRoute: typeof ApiPublicV1ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tasks/$id/nudge': {
      id: '/api/public/v1/tasks/$id/nudge'
      path: '/nudge'
      fullPath: '/api/public/v1/tasks/$id/nudge'
      preLoaderRoute: typeof ApiPublicV1TasksIdNudgeRouteImport
      parentRoute: typeof ApiPublicV1TasksIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicantsRoute: typeof AuthenticatedApplicantsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCompletedRoute: typeof AuthenticatedCompletedRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExecutiveInfoRoute: typeof AuthenticatedExecutiveInfoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicantsRoute: AuthenticatedApplicantsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCompletedRoute: AuthenticatedCompletedRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExecutiveInfoRoute: AuthenticatedExecutiveInfoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1TasksIdRouteChildren {
  ApiPublicV1TasksIdNudgeRoute: typeof ApiPublicV1TasksIdNudgeRoute
}

const ApiPublicV1TasksIdRouteChildren: ApiPublicV1TasksIdRouteChildren = {
  ApiPublicV1TasksIdNudgeRoute: ApiPublicV1TasksIdNudgeRoute,
}

const ApiPublicV1TasksIdRouteWithChildren =
  ApiPublicV1TasksIdRoute._addFileChildren(ApiPublicV1TasksIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1ContactsIdRoute: ApiPublicV1ContactsIdRoute,
  ApiPublicV1TasksIdRoute: ApiPublicV1TasksIdRouteWithChildren,
  ApiPublicV1ContactsIndexRoute: ApiPublicV1ContactsIndexRoute,
  ApiPublicV1TasksIndexRoute: ApiPublicV1TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
